### ISSUE TITLE
Week Nine - Final Project Development 1 

### ISSUE THREAD

**Issue by shreya-ahujaa** [shreya-ahujaa/shreya.individual#9]
### Requirements
- [x] Minimum of 5 hours of Code, Code, Code
- [x]  Review Ticket with Tangibles
- [x]  Tangibles that easily help individuals visualize work in project
- [x]  Scrum Team crossover and Scrum Master
- [x]  Score of 2 points: 1.8 maximum
- [x]  Meeting 5 hours with commit evidence is minumum for .9
- [x]  Meeting team and sponsor objectives

### Tangibles 

- [x] [Adding Navbar Issue](https://github.com/VidhiKulkarni/teamlace/issues/46)
- [x] Themes on [Sign Up/Login Page](https://github.com/VidhiKulkarni/teamlace/commit/6eebb2a0c2c69fc0455aef0f948978e391328487)
- [x] [Started Footer](https://github.com/VidhiKulkarni/teamlace/issues/41) for All Pages
- [x] [Image and Video Gallery](https://github.com/VidhiKulkarni/teamlace/issues/40)
- [x] [Meet Our Team Page ](https://github.com/VidhiKulkarni/teamlace/issues/9)

**Comment by rebecca-123** [comment]
Score: 1.7/2

- Clear planning and organization of future technicals and aspects of project (ie footer,  image/video gallery)
- Future improvement would be more regular commits/contributions but this was difficult during AP exam week
- Met design manager responsibilities of designing website
   - Uniform updates on all pages
